using System.Text;

namespace Server.Database
{
    /// <summary>
    /// 物品管理器(ItemMgrForm)专用中文标签映射.
    /// 仅用于显示层: 数据库中枚举均以数字存储, 此类不影响任何存档数据和其它界面.
    /// 未命中的枚举值回退显示英文原名.
    /// </summary>
    public static class ItemMgrLabels
    {
        public static readonly Dictionary<ItemType, string> TypeNames = new()
        {
            { ItemType.Nothing, "无" },
            { ItemType.Weapon, "武器" },
            { ItemType.Armour, "盔甲" },
            { ItemType.Helmet, "头盔" },
            { ItemType.Necklace, "项链" },
            { ItemType.Bracelet, "手镯" },
            { ItemType.Ring, "戒指" },
            { ItemType.Amulet, "护身符/毒药" },
            { ItemType.Belt, "腰带" },
            { ItemType.Boots, "靴子" },
            { ItemType.Stone, "镶嵌石" },
            { ItemType.Torch, "光源" },
            { ItemType.Potion, "药品" },
            { ItemType.Ore, "矿石" },
            { ItemType.Meat, "肉" },
            { ItemType.CraftingMaterial, "制作材料" },
            { ItemType.Scroll, "卷轴" },
            { ItemType.Gem, "宝石" },
            { ItemType.Mount, "坐骑" },
            { ItemType.Book, "技能书" },
            { ItemType.Script, "脚本物品" },
            { ItemType.Reins, "缰绳" },
            { ItemType.Bells, "铃铛" },
            { ItemType.Saddle, "马鞍" },
            { ItemType.Ribbon, "缎带" },
            { ItemType.Mask, "面具" },
            { ItemType.Food, "食物" },
            { ItemType.Hook, "鱼钩" },
            { ItemType.Float, "鱼漂" },
            { ItemType.Bait, "鱼饵" },
            { ItemType.Finder, "探鱼器" },
            { ItemType.Reel, "鱼线轮" },
            { ItemType.Fish, "鱼" },
            { ItemType.Quest, "任务物品" },
            { ItemType.Awakening, "觉醒材料" },
            { ItemType.Pets, "宠物" },
            { ItemType.Transform, "变身" },
            { ItemType.Deco, "装饰" },
            { ItemType.Socket, "开孔材料" },
            { ItemType.MonsterSpawn, "怪物召唤" },
            { ItemType.SiegeAmmo, "攻城弹药" },
            { ItemType.SealedHero, "封印英雄" },
        };

        public static readonly Dictionary<ItemGrade, string> GradeNames = new()
        {
            { ItemGrade.None, "无" },
            { ItemGrade.Common, "普通" },
            { ItemGrade.Rare, "稀有" },
            { ItemGrade.Legendary, "传说" },
            { ItemGrade.Mythical, "神话" },
            { ItemGrade.Heroic, "英雄" },
        };

        public static readonly Dictionary<RequiredType, string> RequiredTypeNames = new()
        {
            { RequiredType.Level, "等级" },
            { RequiredType.MaxAC, "最大防御" },
            { RequiredType.MaxMAC, "最大魔御" },
            { RequiredType.MaxDC, "最大攻击" },
            { RequiredType.MaxMC, "最大魔法" },
            { RequiredType.MaxSC, "最大道术" },
            { RequiredType.MaxLevel, "最大等级" },
            { RequiredType.MinAC, "最小防御" },
            { RequiredType.MinMAC, "最小魔御" },
            { RequiredType.MinDC, "最小攻击" },
            { RequiredType.MinMC, "最小魔法" },
            { RequiredType.MinSC, "最小道术" },
        };

        public static readonly Dictionary<RequiredClass, string> RequiredClassNames = new()
        {
            { RequiredClass.Warrior, "战士" },
            { RequiredClass.Wizard, "法师" },
            { RequiredClass.Taoist, "道士" },
            { RequiredClass.Assassin, "刺客" },
            { RequiredClass.Archer, "弓手" },
            { RequiredClass.Monk, "武僧" },
            { RequiredClass.WarWizTao, "战法道" },
            { RequiredClass.None, "全职业" },
        };

        public static readonly Dictionary<RequiredGender, string> RequiredGenderNames = new()
        {
            { RequiredGender.Male, "男" },
            { RequiredGender.Female, "女" },
            { RequiredGender.None, "不限" },
        };

        public static readonly Dictionary<ItemSet, string> SetNames = new()
        {
            { ItemSet.None, "无" },
            { ItemSet.Spirit, "圣灵" },
            { ItemSet.Recall, "记忆" },
            { ItemSet.RedOrchid, "红兰" },
            { ItemSet.RedFlower, "红花" },
            { ItemSet.Smash, "粉碎" },
            { ItemSet.HwanDevil, "幻魔" },
            { ItemSet.Purity, "圣洁" },
            { ItemSet.FiveString, "五弦" },
            { ItemSet.Mundane, "世俗" },
            { ItemSet.NokChi, "诺奇" },
            { ItemSet.TaoProtect, "道尊" },
            { ItemSet.Mir, "密尔" },
            { ItemSet.Bone, "白骨" },
            { ItemSet.Bug, "虫族" },
            { ItemSet.WhiteGold, "白金" },
            { ItemSet.WhiteGoldH, "白金(英雄)" },
            { ItemSet.RedJade, "红玉" },
            { ItemSet.RedJadeH, "红玉(英雄)" },
            { ItemSet.Nephrite, "碧玉" },
            { ItemSet.NephriteH, "碧玉(英雄)" },
            { ItemSet.Whisker1, "龙须1" },
            { ItemSet.Whisker2, "龙须2" },
            { ItemSet.Whisker3, "龙须3" },
            { ItemSet.Whisker4, "龙须4" },
            { ItemSet.Whisker5, "龙须5" },
            { ItemSet.Hyeolryong, "血龙" },
            { ItemSet.Monitor, "监视者" },
            { ItemSet.Oppressive, "威压" },
            { ItemSet.Paeok, "贝奥" },
            { ItemSet.Sulgwan, "顺冠" },
            { ItemSet.BlueFrost, "蓝霜" },
            { ItemSet.BlueFrostH, "蓝霜(英雄)" },
            { ItemSet.DarkGhost, "暗鬼" },
        };

        public static readonly Dictionary<BindMode, string> BindNames = new()
        {
            { BindMode.DontDeathdrop, "死亡不掉落" },
            { BindMode.DontDrop, "不可丢弃" },
            { BindMode.DontSell, "不可出售" },
            { BindMode.DontStore, "不可存仓" },
            { BindMode.DontTrade, "不可交易" },
            { BindMode.DontRepair, "不可修理" },
            { BindMode.DontUpgrade, "不可强化" },
            { BindMode.DestroyOnDrop, "丢弃即销毁" },
            { BindMode.BreakOnDeath, "死亡破碎" },
            { BindMode.BindOnEquip, "装备后绑定" },
            { BindMode.NoSRepair, "不可特修" },
            { BindMode.NoWeddingRing, "不可作婚戒" },
            { BindMode.UnableToRent, "不可租赁" },
            { BindMode.UnableToDisassemble, "不可拆解" },
            { BindMode.NoMail, "不可邮寄" },
            { BindMode.NoHero, "不可给英雄" },
        };

        public static readonly Dictionary<SpecialItemMode, string> SpecialNames = new()
        {
            { SpecialItemMode.Paralize, "麻痹" },
            { SpecialItemMode.Teleport, "传送" },
            { SpecialItemMode.ClearRing, "清除" },
            { SpecialItemMode.Protection, "护身" },
            { SpecialItemMode.Revival, "复活" },
            { SpecialItemMode.Muscle, "大力" },
            { SpecialItemMode.Flame, "火焰" },
            { SpecialItemMode.Healing, "治愈" },
            { SpecialItemMode.Probe, "探知" },
            { SpecialItemMode.Skill, "技能" },
            { SpecialItemMode.NoDuraLoss, "不掉持久" },
            { SpecialItemMode.Blink, "闪现" },
        };

        public static readonly Dictionary<Stat, string> StatNames = new()
        {
            { Stat.MinAC, "最小防御" },
            { Stat.MaxAC, "最大防御" },
            { Stat.MinMAC, "最小魔御" },
            { Stat.MaxMAC, "最大魔御" },
            { Stat.MinDC, "最小攻击" },
            { Stat.MaxDC, "最大攻击" },
            { Stat.MinMC, "最小魔法" },
            { Stat.MaxMC, "最大魔法" },
            { Stat.MinSC, "最小道术" },
            { Stat.MaxSC, "最大道术" },
            { Stat.Accuracy, "准确" },
            { Stat.Agility, "敏捷" },
            { Stat.HP, "生命上限" },
            { Stat.MP, "魔法上限" },
            { Stat.AttackSpeed, "攻击速度" },
            { Stat.Luck, "幸运" },
            { Stat.BagWeight, "包裹负重" },
            { Stat.HandWeight, "手腕负重" },
            { Stat.WearWeight, "穿戴负重" },
            { Stat.Reflect, "物理反弹" },
            { Stat.Strong, "强度" },
            { Stat.Holy, "神圣" },
            { Stat.Freezing, "冰冻" },
            { Stat.PoisonAttack, "毒攻击" },
            { Stat.MagicResist, "魔法躲避" },
            { Stat.PoisonResist, "毒物躲避" },
            { Stat.HealthRecovery, "生命恢复" },
            { Stat.SpellRecovery, "魔法恢复" },
            { Stat.PoisonRecovery, "中毒恢复" },
            { Stat.CriticalRate, "暴击率" },
            { Stat.CriticalDamage, "暴击伤害" },
            { Stat.MaxACRatePercent, "最大防御%" },
            { Stat.MaxMACRatePercent, "最大魔御%" },
            { Stat.MaxDCRatePercent, "最大攻击%" },
            { Stat.MaxMCRatePercent, "最大魔法%" },
            { Stat.MaxSCRatePercent, "最大道术%" },
            { Stat.AttackSpeedRatePercent, "攻击速度%" },
            { Stat.HPRatePercent, "生命%" },
            { Stat.MPRatePercent, "魔法%" },
            { Stat.HPDrainRatePercent, "吸血%" },
            { Stat.ExpRatePercent, "经验%" },
            { Stat.ItemDropRatePercent, "物品爆率%" },
            { Stat.GoldDropRatePercent, "金币爆率%" },
            { Stat.MineRatePercent, "挖矿率%" },
            { Stat.GemRatePercent, "宝石率%" },
            { Stat.FishRatePercent, "钓鱼率%" },
            { Stat.CraftRatePercent, "制作率%" },
            { Stat.SkillGainMultiplier, "技能熟练倍率" },
            { Stat.AttackBonus, "攻击加成" },
            { Stat.LoverExpRatePercent, "情侣经验%" },
            { Stat.MentorDamageRatePercent, "师徒伤害%" },
            { Stat.MentorExpRatePercent, "师徒经验%" },
            { Stat.DamageReductionPercent, "伤害减免%" },
            { Stat.EnergyShieldPercent, "能量护盾%" },
            { Stat.EnergyShieldHPGain, "护盾生命获取" },
            { Stat.ManaPenaltyPercent, "魔法惩罚%" },
            { Stat.TeleportManaPenaltyPercent, "传送魔法惩罚%" },
            { Stat.Hero, "英雄" },
            { Stat.Unknown, "未知" },
        };

        public static string Of(ItemType value) => TypeNames.TryGetValue(value, out var s) ? s : value.ToString();
        public static string Of(ItemGrade value) => GradeNames.TryGetValue(value, out var s) ? s : value.ToString();
        public static string Of(RequiredType value) => RequiredTypeNames.TryGetValue(value, out var s) ? s : value.ToString();
        public static string Of(RequiredClass value) => RequiredClassNames.TryGetValue(value, out var s) ? s : value.ToString();
        public static string Of(RequiredGender value) => RequiredGenderNames.TryGetValue(value, out var s) ? s : value.ToString();
        public static string Of(ItemSet value) => SetNames.TryGetValue(value, out var s) ? s : value.ToString();
        public static string Of(BindMode value) => BindNames.TryGetValue(value, out var s) ? s : value.ToString();
        public static string Of(SpecialItemMode value) => SpecialNames.TryGetValue(value, out var s) ? s : value.ToString();
        public static string Of(Stat value) => StatNames.TryGetValue(value, out var s) ? s : value.ToString();

        /// <summary>
        /// 剩余英文物品名 -> 中文 对照表(用于"批量翻译英文名"功能).
        /// 键为当前库中存在的英文名(忽略大小写匹配), 改名时会自动同步 Drops/Recipe/Quests/NPCs 脚本.
        /// </summary>
        public static readonly Dictionary<string, string> EnglishItemNames = new(StringComparer.OrdinalIgnoreCase)
        {
            { "RedJadeBelt", "红玉腰带" },
            { "RedJadeShoes", "红玉靴" },
            { "RedJadeBracelet", "红玉手镯" },
            { "RedJadeRing", "红玉戒指" },
            { "RedJadeBelt(H)", "红玉腰带(H)" },
            { "RedJadeShoes(H)", "红玉靴(H)" },
            { "RedJadeBracelet(H)", "红玉手镯(H)" },
            { "RedJadeRing(H)", "红玉戒指(H)" },
            { "CheongboHelmet(ARCH)", "青布头盔(ARCH)" },
            { "CheongboBelt(ARCH)", "青布腰带(ARCH)" },
            { "CheongboBoots(ARCH)", "青布靴(ARCH)" },
            { "TheRipper", "开膛手" },
            { "WoodenBow", "木弓" },
            { "EbonyBow", "乌木弓" },
            { "ShortBow", "短弓" },
            { "BoneBow", "骨弓" },
            { "CompoundBow", "复合弓" },
            { "LongBow", "长弓" },
            { "SilverBow", "银弓" },
            { "ZumaFiendBow", "祖玛魔弓" },
            { "FiendBow", "魔弓" },
            { "CursedMaleficBow", "诅咒邪弓" },
            { "LitheBow", "轻灵弓" },
            { "MaleficBow", "邪恶弓" },
            { "BowOfForce", "力量之弓" },
            { "DreadBow", "恐惧之弓" },
            { "GrimBow", "冷酷之弓" },
            { "LethalBow", "致命之弓" },
            { "ApusBow", "天燕之弓" },
            { "DeathBow", "死神之弓" },
            { "BloodThirstyBow", "嗜血之弓" },
            { "HardenedRing", "坚硬戒指" },
            { "SurvivalRing", "生存戒指" },
            { "SurvivalBracelet", "生存手镯" },
            { "SurvivalNecklace", "生存项链" },
            { "CraftRing1", "制作戒指1" },
            { "CraftRing2", "制作戒指2" },
            { "CraftRing3", "制作戒指3" },
            { "CraftRing4", "制作戒指4" },
            { "CraftRing5", "制作戒指5" },
            { "CraftRing6", "制作戒指6" },
            { "CraftRing7", "制作戒指7" },
            { "CraftRing8", "制作戒指8" },
            { "CraftRing9", "制作戒指9" },
            { "CraftRing10", "制作戒指10" },
            { "GoldenDragonBrace", "金龙手镯" },
            { "GoldenDragonBrace1", "金龙手镯1" },
            { "GoldenDragonBrace2", "金龙手镯2" },
            { "GoldenDragonBrace3", "金龙手镯3" },
            { "GoldenDragonBrace4", "金龙手镯4" },
            { "GoldenDragonBrace5", "金龙手镯5" },
            { "DragonNecklace", "龙鳞项链" },
            { "DragonNecklace1", "龙鳞项链1" },
            { "DragonNecklace2", "龙鳞项链2" },
            { "DragonNecklace3", "龙鳞项链3" },
            { "DragonNecklace4", "龙鳞项链4" },
            { "DragonNecklace5", "龙鳞项链5" },
            { "DragonPendant", "龙鳞吊坠" },
            { "DragonPendant1", "龙鳞吊坠1" },
            { "DragonPendant2", "龙鳞吊坠2" },
            { "DragonPendant3", "龙鳞吊坠3" },
            { "DragonPendant4", "龙鳞吊坠4" },
            { "DragonPendant5", "龙鳞吊坠5" },
            { "HelmetOfKings", "王者头盔" },
            { "HelmetOfSorcery", "巫术头盔" },
            { "PurifiedMask", "净化面具" },
            { "DemonShadow", "恶魔之影" },
            { "FlamingGrasp", "烈焰之握" },
            { "RottenShoes", "腐朽之靴" },
            { "(HP)PotionMedium", "中级生命药水" },
            { "(MP)PotionMedium", "中级魔法药水" },
            { "SpencerDrug", "斯宾塞药水" },
            { "HerbalTea", "草药茶" },
            { "EnternalFlame", "永恒之火" },
            { "BlueRibbon", "蓝色缎带" },
            { "BlackRibbon", "黑色缎带" },
            { "LeatherMask", "皮革面具" },
            { "WhiteMask", "白色面具" },
            { "BlackMask", "黑色面具" },
            { "SilverMask", "银色面具" },
            { "Tinker", "补锅匠" },
            { "SmallGobby", "小哥布林" },
            { "Mackeral", "鲭鱼" },
            { "Gobby", "哥布林" },
            { "ArmourBook(ACC)", "盔甲书(ACC)" },
            { "Translucent", "半透明石" },
            { "HavocCrystal", "浩劫水晶" },
            { "BookofMana", "魔力之书" },
            { "BookofSpirit", "精神之书" },
            { "ArmourCastTool", "铸甲工具" },
            { "MossyBox", "苔藓宝箱" },
            { "AdamintineOre", "金刚矿石" },
            { "EmeraldOre", "翡翠矿石" },
            { "OlivineOre", "橄榄矿石" },
            { "Feather", "羽毛" },
            { "String", "鱼线" },
            { "HealingLetter", "治愈信笺" },
            { "PigEar", "猪耳朵" },
            { "PigHoof", "猪蹄" },
            { "SpiderLeg", "蜘蛛腿" },
            { "CannibalPoison", "食人毒药" },
            { "AncientLeather", "远古皮革" },
            { "bink", "宾克" },
            { "StiffWoodenBow", "硬木弓" },
            { "StrongWoodenBow", "强化木弓" },
            { "ElkWoodenBow", "麋鹿木弓" },
            { "ToughBow", "坚韧之弓" },
            { "ToughLongBow", "坚韧长弓" },
            { "SolidSilverBow", "坚固银弓" },
            { "RedMoonSword", "红月之剑" },
            { "RedMoonBlades", "红月双刃" },
            { "RedMoonBow", "红月之弓" },
            { "CreditToken1", "点券1" },
            { "CreditToken2", "点券2" },
            { "CreditToken3", "点券3" },
            { "CreditToken4", "点券4" },
            { "CreditToken5", "点券5" },
            { "CreditToken6", "点券6" },
            { "CreditToken7", "点券7" },
            { "CreditToken8", "点券8" },
            { "EXP50%1", "50%经验丹(1小时)" },
            { "EXP50%3", "50%经验丹(3小时)" },
            { "EXP50%5", "50%经验丹(5小时)" },
            { "EXP50%24", "50%经验丹(24小时)" },
            { "EXP100%1", "100%经验丹(1小时)" },
            { "EXP100%3", "100%经验丹(3小时)" },
            { "EXP100%5", "100%经验丹(5小时)" },
            { "EXP100%24", "100%经验丹(24小时)" },
            { "EXP20%[1d]", "20%经验丹(1天)" },
            { "AncientScyther", "远古镰刀" },
            { "Monk Wooden Staff", "武僧木杖" },
            { "Monk Iron Staff", "武僧铁杖" },
            { "Monk Steel Staff", "武僧钢杖" },
            { "Monk Silver Staff", "武僧银杖" },
            { "Monk Golden Staff", "武僧金杖" },
            { "Monk Dragon Staff", "武僧龙杖" },
            { "Monk Cloth Robe", "武僧布袍" },
            { "Monk Leather Robe", "武僧皮袍" },
            { "Monk Iron Robe", "武僧铁袍" },
            { "Monk Silver Robe", "武僧银袍" },
            { "Monk Golden Robe", "武僧金袍" },
            { "Monk Dragon Robe", "武僧龙袍" },
        };
    }
}
